services:
  - postgresql

install:
  - npm install
  - npm uninstall -g typescript # Rely only on the locally installed typescript

before_script:
  - psql -c "CREATE DATABASE \"drewbot-test\"" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'mysecretpassword';" -U postgres

language: node_js
node_js:
  - "8"
  - "9"

script:
  - npm run lint
  - set -e
  - npm run build
  - npm run test-only
